name: Angular S3 Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MY_KEY_AWS_ORE_SECURE }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_SECRET_AWS_ORE_SECURE }}
        run: |
          aws s3 cp \
            --recursive \
              dist/Proyecto-software-chatbot-advisor s3://angularbucketchat
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
