#       ___       __      _                
#      /   | ____/ /   __(_)________  _____
#     / /| |/ __  / | / / / ___/ __ \/ ___/
#    / ___ / /_/ /| |/ / (__  ) /_/ / /    
#   /_/  |_\__,_/ |___/_/____/\____/_/   DEPLOY


name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "angularbucketchat"
  EB_APPLICATION_NAME      : "Mychatbotadvisor"
  EB_ENVIROMENT_NAME       : "Mychatbotadvisor-env"
  DEPLOY_PACKAGE_NAME      : "Proyecto-software-chatbot-advisor- -${{ github.sha }}"
  AWS_REGION_NAME          : "us-west-2"
  
on:
  push:
    branches:
      - master

jobs:
  my_ci_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: AKIARRBYHQ5MQKEQDJ7F
          AWS_SECRET_ACCESS_KEY: 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
        run: |
          aws s3 cp \
            --recursive \
              dist/Proyecto-software-chatbot-advisor s3://angularbucketchat 
              zip ../myapp.zip -r * .[^.]*
              
     
  my_cd_pipeline:    
       runs-on: ubuntu-18.04
       needs: [my_ci_pipeline]
       
       steps:
         - name: Create new ElasticBeanstalk Application Version
           env:
              AWS_ACCESS_KEY_ID: AKIARRBYHQ5MQKEQDJ7F
              AWS_SECRET_ACCESS_KEY: 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
              AWS_REGION: us-west-2
           run: |
             aws elasticbeanstalk create-application-version \
             --application-name Mychatbotadvisor \
             --version-label "ver-${{ github.sha }}" \
             --source-budle S3Bucket="angularbucketchat" 
              
         - name: Deploy our new Aplication Version
           run: aws elasticbeanstalk update-enviroment-name Mychatbotadvisor-env  
         
         - name: Print nice message on completion of cd Pipeline
           run: ech "CD Pipeline part finished successfully"
           
                     
           
